- name: Test Aruba Switch CLI Command
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run show version
      ansible.netcommon.cli_command:
        command: show version
      register: result

    - name: Display result
      debug:
        var: result.stdout_lines

